name: Build and Release

on:
  push:
    tags:
      - "v*"
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: windows
            goarch: amd64
            suffix: .exe
          - goos: windows
            goarch: 386
            suffix: .exe
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - run: go mod tidy
      - env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          mkdir -p dist
          go build -ldflags "-s -w" -o dist/creamapi-dlc-updater-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.suffix }} .
      - uses: actions/upload-artifact@v4
        with:
          name: creamapi-dlc-updater-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/creamapi-dlc-updater-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.suffix }}
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      - name: List artifacts
        run: |
          echo "Listing artifacts directory:"
          find ./artifacts -type f -name "*" | head -20
      - uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/**/*
          draft: false
          prerelease: false
          generate_release_notes: true
          fail_on_unmatched_files: true
          token: ${{ github.token }}
